    create table tb_account (
       id bigint generated by default as identity,
        balance numeric(19,2),
        deposit numeric(19,2),
        client_id bigint,
        primary key (id)
    );
	create table tb_client (
       id bigint generated by default as identity,
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );
	    create table tb_transfer (
       id bigint generated by default as identity,
        amount numeric(19,2),
        from_account_number bigint,
        to_account_number bigint,
        transfer_date TIMESTAMP WITHOUT TIME ZONE,
        primary key (id)
    );